version: 0.2
env:
  secrets-manager:
    GITHUB_TOKEN: $GITHUB_TOKEN_ARN
phases:
  install:
    runtime-versions:
      python: 3.9
    # commands:
  pre_build:
    commands:
      - pip install -r requirements.txt
      - pip install -r dev-requirements.txt
  build:
    commands:
      - ./bin/pdoc.sh
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: 'docs'
  s3-prefix: '/'